import localFont from "next/font/local";
import "./globals.css";

const farsan = localFont({
  src: '../assets/fonts/Farsan-Regular.ttf',
  variable: '--font-farsan',
  display: 'swap'
});

const tradewinds = localFont({
  src: '../assets/fonts/TradeWinds-Regular.ttf',
  variable: '--font-tradewinds',
  display: 'swap',
});

export const metadata = {
  title: "The Shadow Realm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${farsan.variable} ${tradewinds.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
